### PR TITLE
Movement fixes + improvements / Tiny DroppedItem changes

### PR DESCRIPTION
**Pull request by Col-E**
### Whats Changed:

* [Walking up stairs is smoothed](https://my.mixtape.moe/gpzcby.mp4), no longer [instantly teleports you up each block](https://my.mixtape.moe/vbfmpk.mp4)
* Dropped items stack size only shows in debug mode
* Dropped items now [become non-solid when near the player](https://my.mixtape.moe/eyecey.mp4)
   * This allows you to pick up nearby objects through walls like in Terraria

### Whats Fixed:

* You can no longer [spiderpig across the ceiling](https://my.mixtape.moe/lsxkvf.mp4).
* You can now [move in tight spaces](https://my.mixtape.moe/wbtydo.mp4).
* If you somehow manage to get stuck, [you will get squeezed free](https://my.mixtape.moe/rvcrht.mp4).

### Bloopers: 

I messed up these movement fixes a bunch of times. Here's a few of them:

* _["Physics are optional"](https://my.mixtape.moe/bhylry.mp4)_
* _["Boing"](https://my.mixtape.moe/xkxdky.mp4)_
* _["Who needs wall collision? Not me!"](https://my.mixtape.moe/snbwkn.mp4)_

### CODE REVIEW

**Comment by Col-E** [comment]
Do not merge yet. A few more things need fixing.

**Comment by egordorichev** [comment]
Big thanks! Movement is always triky ;) One thing i found in changed files, is that the spawn command description tells: "spawns in an entity". Thats totaly fine, but the code ask Enemies class to do that. Probably,  Enemies should becomd creatures and handle CreatureWithAI. Thats my error. Sorry. Will update that system, when will be back.

**Comment by Col-E** [comment]
Movement sure is a real pain to get just right. Spent pretty much all day trying to fix these bugs. But now I can finally close https://github.com/egordorichev/LastTry/issues/75

**Comment by Col-E** [comment]
I think I haven't broken anything more than I fixed it.  The one disappointing thing is that fix makes going up steps kinda jarring now. The best solution would be to have a camera that lags a little bit behind and moves into position rather than constantly being perfectly centered at the player.

**Comment by egordorichev** [comment]
That can be done easily. Camera moves werid because of int / floats.

**Comment by Col-E** [comment]
The issue is the camera modification is the easy fix. An even better movement implementation would be the best option.

**Comment by Col-E** [comment]
[Working on smoothing out motion while keeping the fixes in place](https://my.mixtape.moe/vwjsby.mp4).

Smoothing is working out nice, but now I can't move in tight places anymore. Looking for a compromise.

**Comment by egordorichev** [comment]
Finaly, i'm here!

**Pull request merged**
