### PR TITLE
Improved splash animation. Improved spawning. Entity collisions.

### PR DESCRIPTION
**Pull request by Col-E**
**What's new**:

* Entity collisions *(`onCollision(Entity)` method in `Entity`, implementation in `Player`)*

**What's changed**:

* Better animation for splash screen *(Fade in, stay, fade out)*
* Better file IO *(Throws exception if an error occurs, automatically closes streams via try-with-resource)*
* Moved Item preloading from `World` constructor to `SplashState`
* Removed `static` modifier on fields that  did not need to be `static`

### CODE REVIEW

**Comment by egordorichev** [comment]
Thank you so much for your help!

**Comment by Col-E** [comment]
I cant get the Codebeat page to fully load so I can't tell what it's complaining about :/

**Comment by egordorichev** [comment]
Do not worry :) some times it is very stupid. But it still gives us A grade.

**Comment by egordorichev** [comment]
Will do more inventory stuff today and also finish `Tool` class.

**Pull request merged**
