### PR TITLE
Entities can now step up walls (Variable for height allowed)

### PR DESCRIPTION
**Pull request by Col-E**
`Entity.stepHeight` allows entities to step up blocks as high as the value goes.

By default it is 1, so players can now [climb up 1-block tall hills](https://my.mixtape.moe/egwiup.png).

### CODE REVIEW

**Comment by egordorichev** [comment]
Thanks! Do they stop, when they step on a block?

**Comment by Col-E** [comment]
What do you mean by stop? 

Here's a [10 second video](https://my.mixtape.moe/rlaqie.mp4) of the step in action. It can only climb up 1-block high walls. If it hits a 2-block high wall it will stop if thats what you're asking.

**Comment by egordorichev** [comment]
Ok, awesome!

**Comment by Col-E** [comment]
Here's a 2-block high wall for [example](https://my.mixtape.moe/jfubho.mp4).

**Comment by egordorichev** [comment]
How do you generate terrain? Is it 1d-perlin noise?

**Comment by Col-E** [comment]
The terrain I showed is just a [cosine](https://github.com/egordorichev/LastTry/blob/master/src/main/java/org/egordorichev/lasttry/world/gen/SimpleWorldGen.java#L11).

**Pull request merged**
